// Platform-side scene paging — Arduboy implementation.
//
// engine/scene.cpp calls into three platform hooks during a state
// transition:
//
//   1. platform_scene_loading_cover(from, to)   — pre-paging visual
//   2. platform_scene_page_in(id)               — Arduboy-only SPM
//                                                  rewrite of the bank
//   3. platform_scene_loading_uncover(from, to) — post-paging visual
//
// Per docs/platform-parity.md, the player-facing visuals (1) and (3)
// are NOT platform-specific — they call into the shared
// games/rpg/transitions.cpp routines. The Arduboy file's only real
// content is the SPM trampoline in (2).
//
// SPM page-in:
//   - Read the scene's cold-copy bytes from FX flash, 128 B at a time.
//   - For each page, call the kp_boot_32u4 SPM trampoline:
//       a. Erase the destination page in internal flash.
//       b. Fill the SPM temporary page buffer with the 64 words read
//          from FX.
//       c. Write the page from the temp buffer to internal flash.
//   - Disable interrupts during each SPM phase (the trampoline itself
//     runs with interrupts disabled internally; we cli/sei around the
//     whole erase-fill-write triplet for one page so a mistimed audio
//     ISR doesn't observe a half-written page).
//
// The cold-copy FX offsets and sizes come from build/fxdata/scene_offsets.h
// (generated by tools/fxdata/scene_extract.py from the OVERLAY-linked ELF).
// The bank base address comes from the linker script (__scene_bank_start).
//
// CPU halt during page-write: SPM RWW-page-write halts the CPU until
// the write completes (~4.5 ms per page). The audio ISR doesn't run
// during that time. Per docs/scene-paging.md, swaps are scheduled on
// transitions where audio silence is expected (title fade, gate card,
// second-death plaque).

#include "audio.h"
#include "data_flash.h"
#include "kp_boot_spm.h"
#include "scene.h"          // scene::Id values
#include "scene_offsets.h"  // scenes::offset_for / size_for, generated
#include "transitions.h"    // shared cover/uncover content
#include "types.h"

extern "C" const u8 __scene_bank_start[];  // linker symbol from scene.ld

namespace {
constexpr u8 PAGE_SIZE = 128;  // ATmega32u4 flash page size
}  // namespace

// Called by engine/scene.cpp's set_active.
extern "C" void platform_scene_page_in(u8 id) {
  const u32 fx_offset = scenes::offset_for(id);
  const u16 size      = scenes::size_for(id);
  if (size == 0) return;  // nothing to load (e.g. an invalid id)

  // Silence the speaker pin BEFORE the SPM loop. The audio ISR will be
  // halted for ~400 ms during page-writes; whatever sample value the
  // voice DACs hold gets driven onto the speaker pin for the entire
  // halt window, producing a fart noise. silence_pins() drives every
  // voice tone to zero but preserves song / SFX state, so the song
  // picks up where it left off on the next tick() after the swap.
  audio::silence_pins();

  const u16 num_pages = (u16)((size + PAGE_SIZE - 1) / PAGE_SIZE);
  u8 page_buf[PAGE_SIZE];
  u16 dest = (u16)(uintptr_t)__scene_bank_start;

  for (u16 p = 0; p < num_pages; ++p) {
    // Read one page worth of bytes from FX into RAM.
    data_flash::read(fx_offset + (u32)p * PAGE_SIZE, page_buf, PAGE_SIZE);

    // SPM phase: erase the page, fill the temp buffer one word at a
    // time, then write the page.
    //
    // Interrupt protection lives INSIDE the SPM trampoline now (see
    // platform/arduboy/spm_app_stub.cpp): cli is held only across the
    // SPMCSR-write + spm instruction pair, and the wait loop runs
    // with interrupts enabled. This is required for Ardens' SPM
    // scheduler to advance (its peripheral-queue callback ticks via
    // the audio ISR firing). Real silicon's SPMEN bit clears on a
    // hardware-fixed schedule regardless of interrupt state, so the
    // same code is safe on hardware. Audio ISR is CORE-resident and
    // doesn't touch SPI / the bank, so no collision risk.
    kp_boot::spm_erase_page(dest);
    for (u8 w = 0; w < PAGE_SIZE / 2; ++w) {
      const u16 word = (u16)page_buf[w * 2] | ((u16)page_buf[w * 2 + 1] << 8);
      kp_boot::spm_load_temporary_buffer((u8)(w * 2), word);
    }
    kp_boot::spm_write_page(dest);

    dest += PAGE_SIZE;
  }
}

// Cover/uncover hooks delegate to the shared transitions module so
// SDL gets the same player-facing behavior with a no-op page_in
// between them (see docs/platform-parity.md).
extern "C" void platform_scene_loading_cover(u8 from_id, u8 to_id) {
  transitions::cover(from_id, to_id);
}

extern "C" void platform_scene_loading_uncover(u8 from_id, u8 to_id) {
  transitions::uncover(from_id, to_id);
}
