#include "Tunables.h"

#include <cstdio>
#include <fstream>

namespace selva::tuning
{

// File-scope singleton. Game starts with the struct's default values; if a
// JSON file exists and parses cleanly, those values overwrite the defaults.
static Tunables sCurrent;

Tunables& current()
{
    return sCurrent;
}

bool loadFromFile(const std::string& path)
{
    std::ifstream f(path);
    if (!f.is_open())
        return false;

    try
    {
        const auto j = nlohmann::json::parse(f);
        // from_json is generated by NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT
        // in Tunables.h. Missing keys fall back to the struct defaults, so
        // older JSON files don't break when new fields are added.
        j.get_to(sCurrent);
        return true;
    }
    catch (const std::exception& ex)
    {
        std::fprintf(stderr, "[Tunables] failed to parse %s: %s\n", path.c_str(), ex.what());
        return false;
    }
}

bool saveToFile(const std::string& path)
{
    nlohmann::json j = sCurrent; // to_json is generated by the same macro
    std::ofstream f(path);
    if (!f.is_open())
        return false;
    f << j.dump(2);
    return f.good();
}

} // namespace selva::tuning
