// Scene dispatch — CORE-resident, engine-side.
//
// All builds (Arduboy + SDL) run the SAME set_active flow per the
// platform-parity doctrine (docs/platform-parity.md):
//
//     on_leave (outgoing) →
//       cover(from, to)         (player-facing cover animation)
//       page_in(id)             (Arduboy: SPM rewrite; SDL: no-op)
//       uncover(from, to)       (player-facing post-paging beat)
//     vtable install →
//     on_enter (incoming)
//
// The cover/uncover hooks call into shared games/<game>/transitions.cpp
// content; only page_in is genuinely platform-specific (Arduboy SPM
// vs SDL no-op). This is what makes player-facing transitions
// identical across platforms — same frame counts, same timing, same
// audio cadence — even though the underlying memory mechanism is
// chip-specific.
//
// The only build difference between paging and non-paging modes is
// where the destination vtable comes from:
//   - Pre-paging (default): the static VT_<NAME> struct passed in `vt`
//     points at functions linked at their actual VMA. set_active just
//     installs the pointer.
//   - Post-paging (`-DSCENE_PAGING_ENABLED`): all four scenes share a
//     VMA via the OVERLAY linker block; on every swap the
//     CORE-resident `active_vtable_storage` is repopulated from the
//     per-scene entry-offset table so callers go through one
//     indirection that the platform can update post-SPM.

#include "scene.h"

#ifdef SCENE_PAGING_ENABLED
#include "progmem.h"  // pgm_read_word for the entry-offset table
#endif

namespace scene {

// Loading-cover animation hook. Called BEFORE page_in so the user
// sees motion in response to the input that triggered the transition
// — masks the ~400 ms SPM freeze on Arduboy (and runs identically on
// SDL with no SPM in between). By the time this returns, the
// framebuffer holds the final "covered" frame.
//
// Implementation: thin shim in platform/<host>/scene_paging.cpp that
// delegates to the shared games/<game>/transitions.cpp content. Both
// platforms' shims are identical body — they exist only because
// engine/ can't directly include game-side headers.
extern "C" void platform_scene_loading_cover(u8 from_id, u8 to_id);

// Loading-uncover hook. Called AFTER page_in, BEFORE the destination
// scene's first update/draw. Holds the cover's final frame for
// additional time (e.g. ~1 s sigil hold + collapse), polls input for
// A-skip, returns when either the hold expires or the user advances.
extern "C" void platform_scene_loading_uncover(u8 from_id, u8 to_id);

#ifdef SCENE_PAGING_ENABLED
// CORE-resident vtable storage. Post-paging, set_active rewrites these
// four fnptrs after each swap. Pre-paging this is unused; `current`
// points directly at the static VT_<NAME> in game.cpp.
static VTable active_vtable_storage;

// Per-scene VTable table indexed by Id. Generated by the cold-copy
// pipeline; fnptrs reference the actual entry-point symbols (linker
// resolves to bank_base + within-scene-offset). Letting the linker
// build the fnptrs avoids hand-rolled byte/word-address conversion.
extern const VTable scene_vtables[ID_COUNT] PROGMEM;

// Implemented in platform/arduboy/scene_paging.cpp. Pages the scene's
// cold-copy bytes from FX flash into the internal-flash swap bank
// using the SPM driver. Called from set_active when the scene id
// changes. Disables interrupts during each page-write phase (see
// kp_boot_spm) — audio ISR pauses for ~400 ms across a swap.
//
// SDL has no SPM (banks are all resident) so its implementation is a
// no-op stub. The cover/uncover beats still play around the no-op,
// keeping player-facing timing identical across platforms.
extern "C" void platform_scene_page_in(u8 id);
#endif

const volatile VTable* current = nullptr;
u8 current_id                  = ID_COUNT;

#ifdef SCENE_PAGING_ENABLED
// Copy the scene's pre-resolved VTable from PROGMEM into the
// CORE-resident `active_vtable_storage`. The fnptrs in the source
// table were resolved by the linker against the actual symbols in
// the OVERLAY layout (bank_base + within-scene-offset), so when the
// bank is paged in with that scene's bytes, calling through these
// fnptrs jumps to the right code with no hand-rolled address math.
static void rewrite_active_vtable(u8 id) {
  // memcpy_P / pgm_read_ptr handle the PROGMEM read portably. We
  // copy 8 bytes (4 fnptrs × 2 bytes each on AVR).
  const VTable* src              = &scene_vtables[id];
  active_vtable_storage.update   = (void (*)())pgm_read_ptr(&src->update);
  active_vtable_storage.draw     = (bool (*)())pgm_read_ptr(&src->draw);
  active_vtable_storage.on_enter = (void (*)())pgm_read_ptr(&src->on_enter);
  active_vtable_storage.on_leave = (void (*)())pgm_read_ptr(&src->on_leave);
}
#endif  // SCENE_PAGING_ENABLED

void set_active(const VTable* vt, u8 id) {
  if (id == current_id) return;  // already resident

  // Drain on_leave on the OUTGOING scene.
  if (current && current->on_leave) current->on_leave();

  // First set_active where id == TITLE is the boot landing.
  // Cover/uncover are skipped (no narrative sense playing Beatrice's
  // exit animation on a fresh power-up). But the page_in is NOT
  // skipped: the bank's resident bytes at reset are whatever the
  // previous run's last SPM left there, which can be ANY scene's
  // bytes (or partial mid-write garbage if the user reset the chip
  // mid-swap). Calling page_in restores TITLE's cold-copy bytes from
  // FX. Without this, boot 2 of a session that swapped past TITLE
  // executes garbage at the bank base — the symptom is white-screen
  // / OOB-deref / OOB-PC depending on what bytes happen to be there.
  // See docs/scene-paging.md "Power loss mid-swap" for the full
  // doctrine — this fixes the case the doc anticipated.
  const bool skip_cover = (current_id == ID_COUNT && id == ID_TITLE);
  if (!skip_cover) {
    platform_scene_loading_cover(current_id, id);
  }

#ifdef SCENE_PAGING_ENABLED
  // Always page in: even on the boot-skip-cover case, we need fresh
  // bytes from FX to overwrite whatever the previous reset left in
  // the bank.
  platform_scene_page_in(id);
#endif

  if (!skip_cover) {
    platform_scene_loading_uncover(current_id, id);
  }

#ifdef SCENE_PAGING_ENABLED
  rewrite_active_vtable(id);
  current = &active_vtable_storage;
  (void)vt;  // ignored under paging — id selects the scene
#else
  current = vt;
#endif
  current_id = id;

  if (current && current->on_enter) current->on_enter();
}

}  // namespace scene
