#!/usr/bin/env python3
"""Bake an existing baked image into tile palette + layout arrays.

Reads <name>_data out of games/rpg/images.cpp, slices it greedy-lossless,
and prints PROGMEM C arrays (palette + layout) to stdout. Pixel-perfect:
the tile reconstruction is byte-identical to the source.

Underscore-prefixed = throwaway dev script. The output goes into
images.cpp by hand and the original raw block is deleted afterward.

    python scripts/_tile_bake.py GATE
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT   = Path(__file__).resolve().parents[1]
IMAGES = ROOT / "games" / "rpg" / "images.cpp"

CANVAS_W = 128
CANVAS_H = 64
TILE_W   = 16
TILE_H   = 16
TILES_X  = CANVAS_W // TILE_W
TILES_Y  = CANVAS_H // TILE_H


def extract_image(name: str) -> bytes:
    text = IMAGES.read_text(encoding="utf-8")
    pat  = re.compile(rf"const u8 {re.escape(name)}_data\[1024\] PROGMEM = \{{(.*?)\}};",
                      re.DOTALL)
    m = pat.search(text)
    if not m:
        raise SystemExit(f"ERROR: {name}_data not found")
    return bytes(int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]+", m.group(1)))


def encode_tile(data: bytes, x0: int, y0: int) -> bytes:
    """Encode a 16×16 region of the source page-major bytes as a 32-byte
    column-major tile (rows 0..7 of cols 0..15, then rows 8..15)."""
    out = bytearray(32)
    for page in range(2):
        for c in range(TILE_W):
            byte = 0
            for bit in range(8):
                y = y0 + page * 8 + bit
                src_byte = data[(y // 8) * CANVAS_W + (x0 + c)]
                if src_byte & (1 << (y & 7)):
                    byte |= 1 << bit
            out[page * TILE_W + c] = byte
    return bytes(out)


def emit_c_array(name: str, data: bytes, per_line: int = 16) -> str:
    lines = [f"const u8 {name}[{len(data)}] PROGMEM = {{"]
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("name", help="image symbol prefix (e.g. GATE)")
    args = ap.parse_args()

    data   = extract_image(args.name)
    tiles  = [encode_tile(data, c * TILE_W, r * TILE_H)
              for r in range(TILES_Y)
              for c in range(TILES_X)]

    # Greedy palette: every unique tile gets one slot, in first-seen order.
    palette: list[bytes] = []
    index_of: dict[bytes, int] = {}
    layout: list[int] = []
    for t in tiles:
        if t not in index_of:
            index_of[t] = len(palette)
            palette.append(t)
        layout.append(index_of[t])

    palette_bytes = b"".join(palette)
    layout_bytes  = bytes(layout)

    print(f"// Auto-generated by scripts/_tile_bake.py from {args.name}_data")
    print(f"// {len(palette)} unique tiles, layout {len(layout_bytes)} B,"
          f" palette {len(palette_bytes)} B (total {len(palette_bytes)+len(layout_bytes)} B"
          f" vs raw 1024 B = saves {1024 - len(palette_bytes) - len(layout_bytes)} B).")
    print()
    print(emit_c_array(f"{args.name}_PALETTE_data", palette_bytes))
    print()
    print(emit_c_array(f"{args.name}_LAYOUT_data", layout_bytes))
    return 0


if __name__ == "__main__":
    sys.exit(main())
