#!/usr/bin/env python3
"""Generate a native-1-bit title image: sun + mountains + cracked ground.
Renders directly to the engine's framebuffer format, no PNG intermediate.
"""

from __future__ import annotations
import argparse
import math

W, H = 128, 64

def emit(name, fb):
    print(f"// 128x64 native-1-bit title image ({len(fb)} bytes, page-major)")
    print(f"// Auto-generated by scripts/gen_title_native.py")
    print(f"const u8 {name}_data[{len(fb)}] PROGMEM = {{")
    for i in range(0, len(fb), 16):
        chunk = fb[i:i+16]
        print("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    print("};")

def make_pixels():
    px = [[False] * W for _ in range(H)]

    # Sun: filled circle in upper-right area
    sun_cx, sun_cy = 92, 16
    sun_r = 9
    for y in range(H):
        for x in range(W):
            if (x - sun_cx) ** 2 + (y - sun_cy) ** 2 <= sun_r * sun_r:
                px[y][x] = True

    # Sun corona: stippled ring
    for theta_deg in range(0, 360, 18):
        theta = math.radians(theta_deg)
        for r in range(sun_r + 2, sun_r + 6):
            x = int(round(sun_cx + r * math.cos(theta)))
            y = int(round(sun_cy + r * math.sin(theta)))
            if 0 <= x < W and 0 <= y < H:
                px[y][x] = True

    # Mountain silhouette: jagged peaks across rows 25..36
    peaks = [
        (0,   34), (8,   30), (15,  27), (22,  31), (30,  25),
        (38,  28), (46,  23), (55,  29), (64,  26), (72,  31),
        (80,  24), (88,  29), (96,  27), (104, 32), (112, 28),
        (120, 30), (127, 33),
    ]
    profile = [37] * W
    for i in range(len(peaks) - 1):
        x0, y0 = peaks[i]
        x1, y1 = peaks[i + 1]
        for x in range(x0, x1 + 1):
            t = (x - x0) / max(1, (x1 - x0))
            profile[x] = int(round(y0 + (y1 - y0) * t))
    for x in range(W):
        for y in range(profile[x], 37):
            px[y][x] = True

    # Horizon line
    for x in range(W):
        px[37][x] = True

    # Foreground: perspective grid + checker fill near bottom
    vp_x = 64
    horizon_y = 37
    for line_idx in range(-5, 6):
        target_x = vp_x + line_idx * 14
        for y in range(horizon_y + 1, H):
            t = (y - horizon_y) / float(H - 1 - horizon_y)
            x = int(round(vp_x + (target_x - vp_x) * t))
            if 0 <= x < W:
                px[y][x] = True
    for k in range(1, 7):
        frac = (k / 6.0) ** 1.6
        y = horizon_y + int(round((H - 1 - horizon_y) * frac))
        if y < H:
            for x in range(W):
                px[y][x] = True

    for y in range(55, H):
        for x in range(W):
            if not px[y][x] and (x + y) % 4 == 0:
                px[y][x] = True

    # Pack to engine format
    fb = bytearray(W * H // 8)
    for page in range(H // 8):
        for x in range(W):
            byte = 0
            for bit in range(8):
                y = page * 8 + bit
                if px[y][x]:
                    byte |= 1 << bit
            fb[page * W + x] = byte
    return bytes(fb)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", default="TITLE_NATIVE")
    args = ap.parse_args()
    emit(args.name, make_pixels())

if __name__ == "__main__":
    main()
