#!/usr/bin/env python3
"""Convert a 1-bit PNG to the engine's column-major, page-major byte format.

The engine stores sprites in PROGMEM as one byte per column-page (8-row
band), then the next page below it, then the next column, and so on. For a
sprite of W columns and H rows:
  - bytes_per_column = ceil(H / 8)
  - total bytes      = W * bytes_per_column
  - storage order    = page-major within column, column-major overall:
      page0 of col0, page0 of col1, ..., page0 of colW-1,
      page1 of col0, page1 of col1, ..., page1 of colW-1, ...

A bit is "on" (drawn as a lit pixel) when the source PNG pixel is non-zero
(white). Black/transparent pixels become "off".

Usage
-----
    python scripts/png_to_sprite.py path/to/sprite.png [--name PLAYER]

Example output (printed to stdout, ready to paste into sprites.cpp):

    // 8x12 from sprite.png
    const u8 PLAYER_data[16] PROGMEM = {
        // page 0 - rows 0..7
        0xC3, 0xE6, 0xF8, 0xFC, 0xFC, 0xF8, 0xE6, 0xC3,
        // page 1 - rows 8..15 (only bits 0..3 used since height=12)
        0x01, 0x0F, 0x0F, 0x01, 0x01, 0x0F, 0x0F, 0x01,
    };
    // widths[PLAYER]  = 8
    // heights[PLAYER] = 12

Tips for drawing in Aseprite
----------------------------
1. File -> New: set Color Mode to "Indexed" and pick the dimensions you want
   (e.g. 8x12 for a player, 5x8 for an enemy).
2. Open the palette (window -> Palette) and edit it down to two entries:
   black (0,0,0) and white (255,255,255).
3. Draw with the white color. Black is "off". The script treats anything
   non-pure-black as on -- but staying strictly two-color is cleanest.
4. File -> Export Sprite Sheet -> just export the single frame as PNG.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.stderr.write(
        "ERROR: Pillow not installed. Install it with:\n"
        "    pacman -S mingw-w64-x86_64-python-pillow\n"
        "or\n"
        "    pip install Pillow\n"
    )
    sys.exit(1)


def png_to_bytes(
    path: Path,
    resize_w: int = 0,
    resize_h: int = 0,
    invert: bool = False,
    autocontrast: bool = False,
    threshold: int = 128,
) -> tuple[int, int, list[int]]:
    """Return (width, height, byte_list) for the sprite at `path`.

    If resize_w/resize_h are non-zero, the source is scaled (preserving
    aspect ratio if only one dim is given) before thresholding. Useful when
    the source PNG is much larger than the target sprite size.
    """
    img = Image.open(path).convert("RGBA")

    # Composite onto white so transparent pixels become "off" (white = bg here,
    # but we'll invert if needed). Most boss source images have transparent
    # backgrounds; without this they'd threshold to noise.
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    img = Image.alpha_composite(bg, img).convert("L")

    if resize_w > 0 or resize_h > 0:
        # Preserve aspect ratio if only one dim specified.
        sw, sh = img.size
        if resize_w == 0:
            resize_w = max(1, int(round(sw * resize_h / sh)))
        if resize_h == 0:
            resize_h = max(1, int(round(sh * resize_w / sw)))
        img = img.resize((resize_w, resize_h), Image.LANCZOS)

    if autocontrast:
        img = ImageOps.autocontrast(img, cutoff=2)

    w, h = img.size
    pages = (h + 7) // 8

    # Read pixels and threshold. invert=True means dark source pixels become
    # "on" (lit) — natural choice for sprites with dark figures on light bg.
    if invert:
        pixels = [[img.getpixel((x, y)) <= threshold for y in range(h)] for x in range(w)]
    else:
        pixels = [[img.getpixel((x, y)) >  threshold for y in range(h)] for x in range(w)]

    out: list[int] = []
    for p in range(pages):
        for x in range(w):
            byte = 0
            for bit in range(8):
                row = p * 8 + bit
                if row >= h:
                    break
                if pixels[x][row]:
                    byte |= 1 << bit
            out.append(byte)
    return w, h, out


def emit_c_array(name: str, width: int, height: int, bytes_: list[int]) -> str:
    pages = (height + 7) // 8
    bytes_per_row = width  # one byte per column per page

    lines: list[str] = []
    lines.append(f"// {width}x{height} sprite (auto-generated by scripts/png_to_sprite.py)")
    lines.append(f"const u8 {name}_data[{len(bytes_)}] PROGMEM = {{")
    for p in range(pages):
        start = p * bytes_per_row
        end   = start + bytes_per_row
        page_bytes = bytes_[start:end]
        if pages > 1:
            top_row = p * 8
            bot_row = min(top_row + 7, height - 1)
            lines.append(f"    // page {p} -- rows {top_row}..{bot_row}")
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in page_bytes) + ",")
    lines.append("};")
    lines.append("")
    lines.append("// In sprites.cpp's tables:")
    lines.append(f"//   widths[{name}]  = {width}")
    lines.append(f"//   heights[{name}] = {height}")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Convert a 1-bit PNG to engine sprite bytes.")
    ap.add_argument("png", type=Path, help="Source PNG file")
    ap.add_argument("--name", default="SPRITE",
                    help="Symbol prefix for the generated array (default: SPRITE)")
    ap.add_argument("--width",  type=int, default=0,
                    help="Resize source to this width (0 = keep original)")
    ap.add_argument("--height", type=int, default=0,
                    help="Resize source to this height (0 = keep original; if only "
                         "one of --width/--height is given, the other is computed to "
                         "preserve aspect ratio)")
    ap.add_argument("--invert", action="store_true",
                    help="Treat dark source pixels as 'on' (use when the figure "
                         "is dark on a light/transparent background)")
    ap.add_argument("--autocontrast", action="store_true",
                    help="Stretch histogram before thresholding")
    ap.add_argument("--threshold", type=int, default=128,
                    help="Pixel brightness cutoff (0..255, default 128)")
    args = ap.parse_args()

    if not args.png.exists():
        sys.stderr.write(f"ERROR: file not found: {args.png}\n")
        return 1

    w, h, data = png_to_bytes(
        args.png,
        resize_w=args.width,
        resize_h=args.height,
        invert=args.invert,
        autocontrast=args.autocontrast,
        threshold=args.threshold,
    )
    if w > 24:
        sys.stderr.write(
            f"WARNING: width is {w} px. The engine's draw_progmem_sprite uses a "
            f"24-byte stack scratch buffer, so widths > 24 will overflow it. "
            f"Either keep width <= 24, or grow the buffer in game.cpp.\n"
        )

    print(emit_c_array(args.name, w, h, data))
    return 0


if __name__ == "__main__":
    sys.exit(main())
