#!/usr/bin/env python3
"""Build the Arduboy FX data image (data.bin) and the matching offset
header (data_offsets.h) from tools/fxdata/manifest.txt.

Inputs (manifest format): see tools/fxdata/manifest.txt header.

Outputs:
    build/fxdata/data.bin      flat byte image, 0..16M offset space.
    build/fxdata/data_offsets.h C++ header with `constexpr u32
                                OFFSET_<NAME>` and `OFFSET_<NAME>_SIZE`
                                per asset. Game code includes this.

Layout policy: byte-packed in manifest order. No alignment, no padding,
no header — the FX driver reads raw bytes from any offset. If we later
need 4-byte alignment for a particular asset class, add it as an
explicit "ALIGN" pragma in the manifest rather than implicit per-asset
padding (so flash-cost regressions are visible at review time).

Sentinel: erased flash reads as 0xFF. Callers should never use 0xFF as
a meaningful asset byte without a length prefix or known size — the
build tool does NOT pad with 0xFF; only the chip's natural state past
the image end is 0xFF.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "tools" / "fxdata" / "manifest.txt"
OUT_DIR = REPO_ROOT / "build" / "fxdata"
DATA_BIN = OUT_DIR / "data.bin"
OFFSETS_H = OUT_DIR / "data_offsets.h"


def parse_manifest(path: Path) -> list[tuple[str, bytes]]:
    """Return [(name, payload_bytes), ...] in manifest order."""
    entries: list[tuple[str, bytes]] = []
    seen: set[str] = set()
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            sys.exit(f"manifest:{lineno}: expected '<name> <source>', got: {raw!r}")
        name, source = parts
        if not name.isidentifier() or not name.isupper():
            sys.exit(f"manifest:{lineno}: name must be UPPER_SNAKE_CASE, got {name!r}")
        if name in seen:
            sys.exit(f"manifest:{lineno}: duplicate name {name!r}")
        seen.add(name)

        if source.startswith("raw:"):
            hex_str = source[len("raw:"):]
            try:
                payload = bytes.fromhex(hex_str)
            except ValueError as e:
                sys.exit(f"manifest:{lineno}: bad raw: hex literal: {e}")
        else:
            asset_path = REPO_ROOT / source
            if not asset_path.is_file():
                sys.exit(f"manifest:{lineno}: file not found: {asset_path}")
            payload = asset_path.read_bytes()

        entries.append((name, payload))
    return entries


def emit_data_bin(entries: list[tuple[str, bytes]], out: Path) -> list[tuple[str, int, int]]:
    """Write data.bin and return [(name, offset, size), ...].

    Pads the image to a 4 KB boundary with 0xFF so that emulators / flash
    tools that assume sector-aligned images don't reject a tiny test
    payload. The trailing 0xFF matches the chip's natural erased state
    so it has no observable effect on game logic.
    """
    out.parent.mkdir(parents=True, exist_ok=True)
    layout: list[tuple[str, int, int]] = []
    payload_total = 0
    with out.open("wb") as f:
        offset = 0
        for name, payload in entries:
            f.write(payload)
            layout.append((name, offset, len(payload)))
            offset += len(payload)
        payload_total = offset
        # Two 4 KB save sectors at the top of the chip for vestigia
        # ping-pong. See engine/data_flash.h save_* + docs/design/
        # "The ledger and the vestigia". MUST stay in lockstep with
        # platform/arduboy/data_flash.cpp's SAVE_BASE (= 0xFFE000)
        # and FX_PAGE_FALLBACK (= 0x20).
        SAVE_REGION = 8192
        DATA_SIZE = 16 * 1024 * 1024 - SAVE_REGION
        if payload_total > DATA_SIZE:
            sys.exit(f"fxdata: payload {payload_total} B exceeds {DATA_SIZE} B (16 MB - 8 KB save)")
        pad = DATA_SIZE - payload_total
        if pad:
            f.write(b"\xFF" * pad)
    return layout


def emit_offsets_h(layout: list[tuple[str, int, int]], out: Path, total_bytes: int) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTOGENERATED by tools/fxdata/build.py — DO NOT EDIT.",
        "// Source of truth: tools/fxdata/manifest.txt.",
        "",
        "#pragma once",
        "",
        "#include \"types.h\"",
        "",
        "namespace fxdata {",
        "",
        f"constexpr u32 IMAGE_SIZE = {total_bytes}u;",
        "",
    ]
    for name, offset, size in layout:
        lines.append(f"constexpr u32 OFFSET_{name}      = {offset}u;")
        lines.append(f"constexpr u16 OFFSET_{name}_SIZE = {size}u;")
    lines.append("")
    lines.append("}  // namespace fxdata")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


# Order MUST match scene::Id in engine/scene.h.
SCENE_NAMES = ("TITLE", "MAIN_MENU", "GATE", "PLAY")


def maybe_append_scene_cold_copies(out_bin: Path, manifest_total: int,
                                    cold_dir: Path) -> list[tuple[str, int, int]]:
    """If `cold.<NAME>.bin` files exist (produced by scene_extract.py
    after the OVERLAY-linked build), append them to data.bin and return
    [(name, offset, size), ...]. The offset is the FX byte where each
    scene's cold copy lives (= manifest end + cumulative scene size).
    Each scene is padded to a 128 B page boundary so the swap manager
    can issue page-aligned reads. Returns an empty list (no append) if
    the cold-copy bins don't exist or are all empty.
    """
    scene_layout: list[tuple[str, int, int]] = []
    cumulative = manifest_total
    PAGE = 128
    with out_bin.open("ab") as f:
        # Pad manifest end to next 128 B boundary so first scene starts
        # page-aligned in flash.
        if cumulative % PAGE:
            pad = PAGE - (cumulative % PAGE)
            f.write(b"\xFF" * pad)
            cumulative += pad
        for name in SCENE_NAMES:
            cold = cold_dir / f"cold.{name}.bin"
            if not cold.exists() or cold.stat().st_size == 0:
                # No cold copy for this scene; record zero size.
                scene_layout.append((name, cumulative, 0))
                continue
            data = cold.read_bytes()
            f.write(data)
            scene_layout.append((name, cumulative, len(data)))
            cumulative += len(data)
            # Pad each scene to a 128 B page boundary so the next scene
            # starts page-aligned.
            if cumulative % PAGE:
                pad = PAGE - (cumulative % PAGE)
                f.write(b"\xFF" * pad)
                cumulative += pad
    return scene_layout


def emit_scene_offsets_h(scene_layout: list[tuple[str, int, int]], out: Path) -> None:
    """Emit build/fxdata/scene_offsets.h. Mirror the structure used by
    tools/fxdata/scene_extract.py's stub mode."""
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTOGENERATED by tools/fxdata/build.py — DO NOT EDIT.",
        "// FX offsets and sizes for each scene's cold copy in data.bin.",
        "",
        "#pragma once",
        "",
        "#include \"types.h\"",
        "#include \"scene.h\"  // scene::Id enum",
        "",
        "namespace scenes {",
        "",
    ]
    for name, off, size in scene_layout:
        lines.append(f"constexpr u32 OFFSET_{name} = {off}u;")
        lines.append(f"constexpr u16 SIZE_{name}   = {size}u;")
    lines.append("")
    lines.append("inline u32 offset_for(u8 id) {")
    lines.append("  switch (id) {")
    for name, _, _ in scene_layout:
        lines.append(f"    case scene::ID_{name}: return OFFSET_{name};")
    lines.append("    default: return 0xFFFFFFFFu;")
    lines.append("  }")
    lines.append("}")
    lines.append("inline u16 size_for(u8 id) {")
    lines.append("  switch (id) {")
    for name, _, _ in scene_layout:
        lines.append(f"    case scene::ID_{name}: return SIZE_{name};")
    lines.append("    default: return 0;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace scenes")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", type=Path, default=MANIFEST)
    ap.add_argument("--out-bin", type=Path, default=DATA_BIN)
    ap.add_argument("--out-header", type=Path, default=OFFSETS_H)
    ap.add_argument("--with-scenes", action="store_true",
                    help="Append scene cold copies (cold.<NAME>.bin from "
                         "build/fxdata/) to data.bin and emit scene_offsets.h. "
                         "Requires scene_extract.py to have run on an "
                         "OVERLAY-linked ELF first.")
    args = ap.parse_args()

    entries = parse_manifest(args.manifest)
    layout = emit_data_bin(entries, args.out_bin)
    total = sum(size for _, _, size in layout)
    emit_offsets_h(layout, args.out_header, total)

    print(f"fxdata: {len(entries)} asset(s), {total} B total")
    for name, offset, size in layout:
        print(f"  OFFSET_{name:<24} = 0x{offset:06X}  ({size} B)")

    if args.with_scenes:
        # NOTE: emit_data_bin pads to 16 MB - 4 KB. We can't simply
        # append; need to truncate to the payload end first, append
        # scene cold copies, then re-pad to 16 MB - 4 KB.
        OUT_DIR_local = args.out_bin.parent
        # Truncate existing data.bin to its payload end.
        with args.out_bin.open("rb+") as f:
            f.truncate(total)
        scene_layout = maybe_append_scene_cold_copies(
            args.out_bin, total, OUT_DIR_local
        )
        # Re-pad to 16 MB - 8 KB (two ping-pong save sectors reserved).
        with args.out_bin.open("ab") as f:
            cur = args.out_bin.stat().st_size
            DATA_SIZE = 16 * 1024 * 1024 - 8192
            if cur > DATA_SIZE:
                sys.exit(f"fxdata: payload {cur} B exceeds {DATA_SIZE} B with scenes appended")
            f.write(b"\xFF" * (DATA_SIZE - cur))
        emit_scene_offsets_h(scene_layout, OUT_DIR_local / "scene_offsets.h")
        print("fxdata: scenes appended:")
        for name, off, size in scene_layout:
            print(f"  SCENE_{name:<10}  offset 0x{off:06X}  size {size} B")
        print(f"  -> {(OUT_DIR_local / 'scene_offsets.h').relative_to(REPO_ROOT)}")

    print(f"  -> {args.out_bin.relative_to(REPO_ROOT)}")
    print(f"  -> {args.out_header.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
