#!/usr/bin/env python3
"""Regenerate config/hair_styles.json from the on-disk hair asset library.

Walks assets/characters/hair/{cc0,ccby}/<style>/humanoid_male_hair.glb,
buckets each style as "short" or "long" (keyword heuristic +
FORCE_LONG/FORCE_SHORT overrides), assigns Short N / Long N display
names, and writes the registry JSON.

Rerun this whenever a hair asset is added, removed, or reclassified.
The runtime C++ loader (selva::hair::loadHairRegistry) reads the JSON
verbatim -- no other code changes needed for a new hair asset.
"""

import os
import json

ABS = os.path.join(os.path.dirname(__file__), "..", "assets", "characters", "hair")
ABS = os.path.abspath(ABS)
REL = "assets/characters/hair"

# Manual reclassifications for styles the keyword heuristic gets wrong.
# Any id in FORCE_LONG goes to the long bucket; FORCE_SHORT to short.
# Alex-driven updates land here.
FORCE_LONG = {
    "cc0/toigo_blunt_bob_with_bangs",
    "cc0/toigo_curled_under_bob_with_bangs",
    "cc0/toigo_inverted_bob_with_bangs",
}
FORCE_SHORT: set = set()

LONG_KEYWORDS = [
    "long", "braid", "hippy", "hippie", "updo", "bun", "cloud", "ponytail",
    "adrienne", "ashley", "daisy", "hazel", "island_princess", "katherine",
    "keylth", "lara", "maxwell", "witchy_lil_bob", "wavy", "lady",
    "grump", "80s", "50s", "junglebook", "reverse_french_braid_bun",
    "unkempt_french_braid", "french_braid", "double_mh_braid",
    "strawberry_cloud", "learning_anime", "faydaen", "shaggy_green",
    "sonntag78_blond_with_headband",
]
SHORT_KEYWORDS = [
    "short", "bob", "afro", "messy", "bangs", "bobcut",
    "littleright", "curled_under", "blunt", "inverted",
    "with_bangs", "rehmanpolanski_hair_bun_brown",
]


def bucket(full_id: str) -> str:
    if full_id in FORCE_LONG:
        return "long"
    if full_id in FORCE_SHORT:
        return "short"
    s = full_id.lower()
    for kw in SHORT_KEYWORDS:
        if kw in s:
            return "short"
    for kw in LONG_KEYWORDS:
        if kw in s:
            return "long"
    return "long"


def main() -> int:
    styles = []
    for lic in ["cc0", "ccby"]:
        lic_dir = os.path.join(ABS, lic)
        if not os.path.isdir(lic_dir):
            continue
        for style_id in sorted(os.listdir(lic_dir)):
            style_dir = os.path.join(lic_dir, style_id)
            if not os.path.isdir(style_dir):
                continue
            if not os.path.isfile(os.path.join(style_dir, "humanoid_male_hair.glb")):
                continue
            full_id = f"{lic}/{style_id}"
            styles.append(
                {
                    "id": full_id,
                    "license": lic,
                    "mesh_path_male": f"{REL}/{lic}/{style_id}/humanoid_male_hair.glb",
                    "length": bucket(full_id),
                }
            )

    short_list = [s for s in styles if s["length"] == "short"]
    long_list = [s for s in styles if s["length"] == "long"]

    # Pin cc0/short01 as the very first short entry (creator default = "first short").
    for i, s in enumerate(short_list):
        if s["id"] == "cc0/short01" and i > 0:
            short_list.insert(0, short_list.pop(i))
            break

    for i, s in enumerate(short_list, 1):
        s["display_name"] = f"Short {i}"
    for i, s in enumerate(long_list, 1):
        s["display_name"] = f"Long {i}"

    reg = {
        "_comment": (
            "Hair style registry. Loaded at boot into selva::hair::hairRegistry(). "
            "Regenerated by scripts/regen_hair_registry.py. Buckets by length "
            "(short/long) with a keyword heuristic + FORCE_LONG/FORCE_SHORT "
            "manual overrides. Short 1 = cc0/short01, the creator default."
        ),
        "styles": short_list + long_list,
    }

    out = os.path.join(os.path.dirname(__file__), "..", "config", "hair_styles.json")
    out = os.path.abspath(out)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(reg, f, indent=2)
    print(f"wrote {out}")
    print(f"  short: {len(short_list)}")
    print(f"  long:  {len(long_list)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
